---
title: "Figure S21"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(Racmacs)
library(r3js)
library(ggplot2)
library(plotly)
```

Inputs {.sidebar}
-------------------------------------
<font size="2">
**Maps showing the uncertainty of the placements of variants and sera.** **A)** Antigenic map with error lines. For each titration, error lines are drawn between the variants and the serum that show the target distance between the variant and serum. Blue lines indicate a target distance shorter than the distance between the variant and serum in the map, red lines indicate that the distance on the map is shorter than the distance in the table. **B)** Triangulation blobs. The colored region for each serum and variant point indicates the area which the variant or serum can occupy without the stress of the map increasing by more than one unit. For color correspondence of variants and sera, refer to Fig. 3.
</font>


Column
-------------------------------------

### A.
```{r}
map <- read.acmap("../../data/maps/map_ndsubset_no_outliers_slope_adjusted.ace")
agSize(map) <- agSize(map)*0.6
srSize(map) <- srSize(map)*0.6

Racmacs::view(
  map,
  options = list(show.errorlines = T)
)
```

Column
-------------------------------------

### B.
```{r}
Racmacs::view(
  readRDS("../../figures/som/figS21b-triangulation_blobs.rds")
)
```
