---
title: "Figure S18"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(Racmacs)
library(r3js)
library(ggplot2)
library(plotly)
```

Inputs {.sidebar}
-------------------------------------
<font size="2">
**Assessing the robustness of the antigenic map to the inclusion of particular titer measurements.** 1000 bootstrap repeats were performed where a random sample of titers were taken with replacement. **A)** Bootstrapping is applied to variants and sera. **B)** Bootstrapping is applied to variants only. **C)** Bootstrapping is applied to sera only. Each colored region indicates the area in which 68% (one standard deviation) of the positional variation of a serum or variant position is captured. Triangles indicate the positions of variants and sera that are outside the area of the plot. For color correspondence of variants and sera, refer to Fig. 3.
</font>


Column
-------------------------------------

### A.
```{r}
Racmacs::view(
  readRDS("../../data/generated_data/map_bootstrap_resample_ags_srs.rds")
)
```

Column
-------------------------------------

### B.
```{r}
Racmacs::view(
  readRDS("../../data/generated_data/map_bootstrap_resample_srs.rds")
)
```

Column
-------------------------------------

### B.
```{r}
Racmacs::view(
  readRDS("../../data/generated_data/map_bootstrap_resample_ags.rds")
)
```
